CREATE TABLE USERS(
	ID SERIAL,
	USERNAME VARCHAR(30),
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	CONTACT_NO BIGINT,
	EMAIL VARCHAR(30),

	PRIMARY KEY (ID),
	UNIQUE (USERNAME)
);

CREATE TABLE ACTIVITY(
	ID SERIAL,
	NAME VARCHAR(50),

	PRIMARY KEY (ID)
);

CREATE TABLE INTERESTS(
	UID INT,
	AID INT,
	PRIOR INT,

	FOREIGN KEY (UID) REFERENCES USERS(ID),
	FOREIGN KEY (AID) REFERENCES ACTIVITY(ID),

	UNIQUE (UID, AID)
);